name: Slack Notifier

on:
  deployment_status

jobs:
  notify_slack:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        run: |
          curl -X POST --data '{"text": "\n:rocket:*Production Deploy Complete*:rocket:\nhttps://github.com/SignalOpsIO/sass-dash-prod/actions/workflows/pages/pages-build-deployment\n"}' ${{ secrets.WEBHOOK }}
  
